# Generated by Django 5.0.6 on 2024-07-09 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
